### ISSUE TITLE
Please expose logs via GET /actuator/logs

### ISSUE THREAD

**Issue by stefanbente** [The-Microservice-Dungeon/map#99]
See code snippet and explanation at

https://discord.com/channels/692269970373214208/886904348486017035/927497233065181244

(if this is easily doable outside a Spring environment - otherwise you can close this issue)

**Comment by daskycodes** [comment]
@stefanbente our logs are exposed through the `/logs` endpoint. Since actuator is a spring related term, I left the `/actuator` out of the endpoint naming.
